// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RockSchool.Data.Data;

#nullable disable

namespace RockSchool.Data.Migrations
{
    [DbContext(typeof(RockSchoolContext))]
    [Migration("20260127171806_Added_BandId_To_Schedules")]
    partial class Added_BandId_To_Schedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisciplineEntityTeacherEntity", b =>
                {
                    b.Property<int>("DisciplinesDisciplineId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeachersTeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("DisciplinesDisciplineId", "TeachersTeacherId");

                    b.HasIndex("TeachersTeacherId");

                    b.ToTable("DisciplineEntityTeacherEntity");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.AttendanceEntity", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttendanceType")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("AttendanceId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("RoomId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.BandEntity", b =>
                {
                    b.Property<Guid>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("BandId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.BandStudentEntity", b =>
                {
                    b.Property<Guid>("BandStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uuid");

                    b.Property<int>("BandRoleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("BandStudentId");

                    b.HasIndex("BandId");

                    b.HasIndex("StudentId");

                    b.ToTable("BandStudents");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.BranchEntity", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Address = "Абая 137",
                            Name = "На Абая",
                            Phone = "77471237896"
                        },
                        new
                        {
                            BranchId = 2,
                            Address = "Аль-Фараби 15",
                            Name = "На Аль-Фараби",
                            Phone = "77471237896"
                        });
                });

            modelBuilder.Entity("RockSchool.Data.Entities.DisciplineEntity", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DisciplineId");

                    b.ToTable("Disciplines");

                    b.HasData(
                        new
                        {
                            DisciplineId = 1,
                            IsActive = true,
                            Name = "Guitar"
                        },
                        new
                        {
                            DisciplineId = 2,
                            IsActive = true,
                            Name = "Electric Guitar"
                        },
                        new
                        {
                            DisciplineId = 3,
                            IsActive = true,
                            Name = "Bass Guitar"
                        },
                        new
                        {
                            DisciplineId = 4,
                            IsActive = true,
                            Name = "Ukulele"
                        },
                        new
                        {
                            DisciplineId = 5,
                            IsActive = true,
                            Name = "Vocal"
                        },
                        new
                        {
                            DisciplineId = 6,
                            IsActive = true,
                            Name = "Drums"
                        },
                        new
                        {
                            DisciplineId = 7,
                            IsActive = true,
                            Name = "Piano"
                        },
                        new
                        {
                            DisciplineId = 8,
                            IsActive = true,
                            Name = "Violin"
                        },
                        new
                        {
                            DisciplineId = 9,
                            IsActive = true,
                            Name = "Extreme Vocal"
                        });
                });

            modelBuilder.Entity("RockSchool.Data.Entities.NoteEntity", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualCompleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("NoteId");

                    b.HasIndex("BranchId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.RoleEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsActive = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            IsActive = false,
                            RoleName = "Teacher"
                        },
                        new
                        {
                            RoleId = 3,
                            IsActive = false,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("RockSchool.Data.Entities.RoomEntity", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("SupportsRehearsal")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsRent")
                        .HasColumnType("boolean");

                    b.HasKey("RoomId");

                    b.HasIndex("BranchId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            BranchId = 1,
                            IsActive = true,
                            Name = "Гитарная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 2,
                            BranchId = 1,
                            IsActive = true,
                            Name = "Вокальная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 4,
                            BranchId = 1,
                            IsActive = true,
                            Name = "Барабанная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 5,
                            BranchId = 1,
                            IsActive = true,
                            Name = "Желтая",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 6,
                            BranchId = 1,
                            IsActive = true,
                            Name = "Зелёная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 10,
                            BranchId = 2,
                            IsActive = true,
                            Name = "Гитарная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 11,
                            BranchId = 2,
                            IsActive = true,
                            Name = "Вокальная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 12,
                            BranchId = 2,
                            IsActive = true,
                            Name = "Барабанная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 13,
                            BranchId = 2,
                            IsActive = true,
                            Name = "Плакатная",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        },
                        new
                        {
                            RoomId = 14,
                            BranchId = 2,
                            IsActive = true,
                            Name = "Желтая",
                            Status = 1,
                            SupportsRehearsal = false,
                            SupportsRent = false
                        });
                });

            modelBuilder.Entity("RockSchool.Data.Entities.ScheduleEntity", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BandId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("ScheduleId");

                    b.HasIndex("BandId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.ScheduledWorkingPeriodEntity", b =>
                {
                    b.Property<Guid>("ScheduledWorkingPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkingPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduledWorkingPeriodId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("WorkingPeriodId");

                    b.ToTable("ScheduledWorkingPeriods");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.StudentEntity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWaiting")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<short>("Sex")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("StudentId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountOutstanding")
                        .HasColumnType("numeric");

                    b.Property<int>("AttendanceCount")
                        .HasColumnType("integer");

                    b.Property<int>("AttendanceLength")
                        .HasColumnType("integer");

                    b.Property<int>("AttendancesLeft")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TrialStatus")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("BranchId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TariffId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TariffEntity", b =>
                {
                    b.Property<Guid>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("AttendanceCount")
                        .HasColumnType("integer");

                    b.Property<int>("AttendanceLength")
                        .HasColumnType("integer");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("integer");

                    b.HasKey("TariffId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            TariffId = new Guid("107f43b0-46c0-4b5f-a6e0-58658a4d0aa8"),
                            Amount = 2000m,
                            AttendanceCount = 1,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 1
                        },
                        new
                        {
                            TariffId = new Guid("1605538b-4e77-4dda-a492-44040dee1ea0"),
                            Amount = 9000m,
                            AttendanceCount = 1,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("1916fc99-d9d4-4b48-a30a-07f2b8271224"),
                            Amount = 30000m,
                            AttendanceCount = 4,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("21a7e82a-b0fd-4e34-8d01-cce816ed34ba"),
                            Amount = 54000m,
                            AttendanceCount = 8,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("24e75034-ebed-44e7-a44c-ea12e33a6767"),
                            Amount = 74000m,
                            AttendanceCount = 12,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("2c45b82e-16dc-4bf2-bd78-eb5922cbe3ec"),
                            Amount = 11000m,
                            AttendanceCount = 1,
                            AttendanceLength = 1,
                            DisciplineId = 9,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("32cfcefc-803e-4922-b358-6a9add488aab"),
                            Amount = 42000m,
                            AttendanceCount = 4,
                            AttendanceLength = 1,
                            DisciplineId = 9,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("3b5a0821-8663-4e1b-8fcc-b48c03d97185"),
                            Amount = 69000m,
                            AttendanceCount = 8,
                            AttendanceLength = 1,
                            DisciplineId = 9,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("6ee39316-06f7-4c1b-9167-f35c3dce5f80"),
                            Amount = 96000m,
                            AttendanceCount = 12,
                            AttendanceLength = 1,
                            DisciplineId = 9,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 0
                        },
                        new
                        {
                            TariffId = new Guid("83a26ae5-6cda-4877-95ab-ddca0b064578"),
                            Amount = 24000m,
                            AttendanceCount = 4,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 2
                        },
                        new
                        {
                            TariffId = new Guid("8d9e7ed0-9dcf-4686-bbf3-744f804d0826"),
                            Amount = 36000m,
                            AttendanceCount = 8,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 2
                        },
                        new
                        {
                            TariffId = new Guid("a57918be-0f1c-41c6-bc2d-add554ac2969"),
                            Amount = 35000m,
                            AttendanceCount = 4,
                            AttendanceLength = 1,
                            DisciplineId = 9,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 2
                        },
                        new
                        {
                            TariffId = new Guid("adcf2ba3-588c-46d8-bab6-04b3a54c2a1d"),
                            Amount = 59000m,
                            AttendanceCount = 8,
                            AttendanceLength = 1,
                            DisciplineId = 9,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 2
                        },
                        new
                        {
                            TariffId = new Guid("af7b2695-618a-4cf3-b57b-14e6aadc0187"),
                            Amount = 24000m,
                            AttendanceCount = 4,
                            AttendanceLength = 3,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 4
                        },
                        new
                        {
                            TariffId = new Guid("becf83b9-bb78-4130-a654-c17c2f7a869a"),
                            Amount = 3000m,
                            AttendanceCount = 1,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 3
                        },
                        new
                        {
                            TariffId = new Guid("ddf4bb6c-686a-490e-9440-61c5e2e68513"),
                            Amount = 11000m,
                            AttendanceCount = 4,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 3
                        },
                        new
                        {
                            TariffId = new Guid("eaa18e35-d9a5-41b0-946b-7557fdc199a8"),
                            Amount = 20000m,
                            AttendanceCount = 8,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 3
                        },
                        new
                        {
                            TariffId = new Guid("f79be13e-77ae-4728-b1ce-6e922c9b066d"),
                            Amount = 30000m,
                            AttendanceCount = 12,
                            AttendanceLength = 1,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SubscriptionType = 3
                        });
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TeacherDisciplineEntity", b =>
                {
                    b.Property<Guid>("TeacherDisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("TeacherDisciplineId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherDisciplines");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TeacherEntity", b =>
                {
                    b.Property<Guid>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowBands")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowGroupLessons")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TeacherId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TenderEntity", b =>
                {
                    b.Property<Guid>("TenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaidOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TenderType")
                        .HasColumnType("integer");

                    b.HasKey("TenderId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.WaitingScheduleEntity", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("WaitingSchedules");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.WorkingPeriodEntity", b =>
                {
                    b.Property<Guid>("WorkingPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("WorkingPeriodId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.ToTable("WorkingPeriods");
                });

            modelBuilder.Entity("DisciplineEntityTeacherEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.DisciplineEntity", null)
                        .WithMany()
                        .HasForeignKey("DisciplinesDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", null)
                        .WithMany()
                        .HasForeignKey("TeachersTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RockSchool.Data.Entities.AttendanceEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BranchEntity", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.DisciplineEntity", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId");

                    b.HasOne("RockSchool.Data.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.SubscriptionEntity", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Branch");

                    b.Navigation("Discipline");

                    b.Navigation("Room");

                    b.Navigation("Student");

                    b.Navigation("Subscription");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.BandEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", "Teacher")
                        .WithMany("Bands")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.BandStudentEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BandEntity", "Band")
                        .WithMany("BandStudents")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.StudentEntity", "Student")
                        .WithMany("BandStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.NoteEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BranchEntity", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.RoomEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BranchEntity", "Branch")
                        .WithMany("Rooms")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.ScheduleEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BandEntity", "Band")
                        .WithMany("Schedules")
                        .HasForeignKey("BandId");

                    b.HasOne("RockSchool.Data.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.SubscriptionEntity", "Subscription")
                        .WithMany("Schedules")
                        .HasForeignKey("SubscriptionId");

                    b.Navigation("Band");

                    b.Navigation("Room");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.ScheduledWorkingPeriodEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", "Teacher")
                        .WithMany("ScheduledWorkingPeriods")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.WorkingPeriodEntity", "WorkingPeriod")
                        .WithMany("ScheduledWorkingPeriods")
                        .HasForeignKey("WorkingPeriodId");

                    b.Navigation("Room");

                    b.Navigation("Teacher");

                    b.Navigation("WorkingPeriod");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.StudentEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BranchEntity", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("RockSchool.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BranchEntity", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.DisciplineEntity", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId");

                    b.HasOne("RockSchool.Data.Entities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.TariffEntity", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId");

                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Branch");

                    b.Navigation("Discipline");

                    b.Navigation("Student");

                    b.Navigation("Tariff");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TariffEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.DisciplineEntity", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId");

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TeacherDisciplineEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.DisciplineEntity", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TeacherEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.BranchEntity", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TenderEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.SubscriptionEntity", "Subscription")
                        .WithMany("Tenders")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.RoleEntity", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.WaitingScheduleEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.DisciplineEntity", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.StudentEntity", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.WorkingPeriodEntity", b =>
                {
                    b.HasOne("RockSchool.Data.Entities.RoomEntity", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RockSchool.Data.Entities.TeacherEntity", "Teacher")
                        .WithMany("WorkingPeriods")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.BandEntity", b =>
                {
                    b.Navigation("BandStudents");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.BranchEntity", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.StudentEntity", b =>
                {
                    b.Navigation("BandStudents");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Tenders");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.TeacherEntity", b =>
                {
                    b.Navigation("Bands");

                    b.Navigation("ScheduledWorkingPeriods");

                    b.Navigation("WorkingPeriods");
                });

            modelBuilder.Entity("RockSchool.Data.Entities.WorkingPeriodEntity", b =>
                {
                    b.Navigation("ScheduledWorkingPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
