stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:24.0.5
  variables:
    TZ: Asia/Almaty
  script:
    - BUILD_TAG=$(date +"%Y%m%d-%H%M%S")
    - IMAGE_TAG="${BUILD_TAG}-${CI_COMMIT_SHORT_SHA}"
    - echo "Using image tag: $IMAGE_TAG"
    - docker info
    - docker build --pull -t rockschool-api:$IMAGE_TAG -t rockschool-api:latest -f Dockerfile .
  only:
    - main
    - master